FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-common.txt requirements-backtest.txt ./
RUN pip install --no-cache-dir -r requirements-backtest.txt

COPY backtest_app ./backtest_app
COPY shared ./shared
COPY tests ./tests

ENTRYPOINT ["python", "-m", "backtest_app.runner"]
