"""update_broker_order_schema

Revision ID: 00de7cf275f8
Revises: 4d48766ca42d
Create Date: 2025-10-03 00:42:42.977013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00de7cf275f8'
down_revision: Union[str, Sequence[str], None] = '4d48766ca42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_order', sa.Column('order_number', sa.Text(), nullable=True, comment='주문번호'), schema='trading')
    op.add_column('broker_order', sa.Column('korea_exchange_order_org_no', sa.Text(), nullable=True, comment='한국거래소전송주문조직번호'), schema='trading')
    op.alter_column('broker_order', 'leg_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='레그ID(FK) - 직접 주문시 NULL 가능',
               existing_comment='레그ID(FK)',
               schema='trading')
    op.drop_index(op.f('ix_broker_order_broker_order_uid'), table_name='broker_order', schema='trading')
    op.create_index('ix_broker_order_order_number', 'broker_order', ['order_number'], unique=False, schema='trading')
    op.drop_column('broker_order', 'ord_dvsn', schema='trading')
    op.drop_column('broker_order', 'broker_order_uid', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_order', sa.Column('broker_order_uid', sa.TEXT(), autoincrement=False, nullable=True, comment='브로커주문고유ID'), schema='trading')
    op.add_column('broker_order', sa.Column('ord_dvsn', sa.TEXT(), autoincrement=False, nullable=False, comment='브로커 주문구분(00/34 등)'), schema='trading')
    op.drop_index('ix_broker_order_order_number', table_name='broker_order', schema='trading')
    op.create_index(op.f('ix_broker_order_broker_order_uid'), 'broker_order', ['broker_order_uid'], unique=False, schema='trading')
    op.alter_column('broker_order', 'leg_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='레그ID(FK)',
               existing_comment='레그ID(FK) - 직접 주문시 NULL 가능',
               schema='trading')
    op.drop_column('broker_order', 'korea_exchange_order_org_no', schema='trading')
    op.drop_column('broker_order', 'order_number', schema='trading')
    # ### end Alembic commands ###
