"""cleaning

Revision ID: 00fe5afe5cfa
Revises: 5a6a7b2f796f
Create Date: 2025-09-29 08:06:19.728909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00fe5afe5cfa'
down_revision: Union[str, Sequence[str], None] = '5a6a7b2f796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_fundamentals', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_fundamentals',
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True, comment='섹터'),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True, comment='산업'),
    sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='시가총액'),
    sa.Column('beta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='베타'),
    sa.Column('trailing_pe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='후행 PER'),
    sa.Column('forward_pe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='선행 PER'),
    sa.Column('trailing_eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='후행 EPS'),
    sa.Column('price_to_book', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='PBR'),
    sa.Column('dividend_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='배당률'),
    sa.Column('dividend_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='배당수익률'),
    sa.Column('payout_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='배당성향'),
    sa.Column('profit_margins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='순이익률'),
    sa.Column('fifty_two_week_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='52주 최고가'),
    sa.Column('fifty_two_week_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='52주 최저가'),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='최종 업데이트일시'),
    schema='trading'
    )
    # ### end Alembic commands ###
