"""add asset snapshot tables

Revision ID: 0b5ed7204e68
Revises: d878e24ea28b
Create Date: 2025-10-06 07:15:50.391973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5ed7204e68'
down_revision: Union[str, Sequence[str], None] = 'd878e24ea28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='스냅샷 고유 ID'),
    sa.Column('asof_kst', sa.DateTime(timezone=True), nullable=False, comment='스냅샷 기준 시각 (KST 기준)'),
    sa.Column('market', sa.String(length=10), nullable=False, comment='시장 구분 (KR/OVRS)'),
    sa.Column('account_uid', sa.Text(), nullable=False, comment='계좌 식별자 (CANO-ACNT_PRDT_CD 조합)'),
    sa.Column('base_ccy', sa.Text(), nullable=False, comment='계좌 기준 통화 (KRW 또는 USD 등)'),
    sa.Column('cash_balance_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='예수금 (출금 가능 현금)'),
    sa.Column('buying_power_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='매수가능금액 (가용자금, 미수 미포함 기준)'),
    sa.Column('total_market_value_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='총 보유 종목 평가금액 (유가증권 평가액)'),
    sa.Column('total_equity_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='총자산금액 (현금 + 평가금액 등)'),
    sa.Column('pnl_amount_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='총평가손익금액'),
    sa.Column('pnl_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='총평가손익률(%)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시 (서버 입력 기준)'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    schema='trading'
    )
    op.create_table('position_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='보유 종목 스냅샷 고유 ID'),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False, comment='계좌 스냅샷 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=True, comment='내부 종목 ID (티커 마스터 FK)'),
    sa.Column('symbol', sa.Text(), nullable=True, comment='종목심볼 또는 상품번호 (pdno)'),
    sa.Column('exchange_code', sa.Text(), nullable=False, comment='거래소 코드 (KOE, NASD, NYSE 등)'),
    sa.Column('position_ccy', sa.Text(), nullable=False, comment='포지션 통화 (KRW, USD, HKD, …)'),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False, comment='보유수량 (체결 기준)'),
    sa.Column('orderable_qty', sa.Numeric(precision=20, scale=8), nullable=True, comment='주문가능수량'),
    sa.Column('avg_cost_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='매입평균단가'),
    sa.Column('last_price_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='현재가'),
    sa.Column('market_value_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='평가금액 (현재가 × 보유수량)'),
    sa.Column('unrealized_pnl_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='평가손익금액'),
    sa.Column('pnl_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='평가손익률(%)'),
    sa.Column('fx_krw_per_ccy', sa.Numeric(precision=20, scale=8), nullable=True, comment='환율 (1통화당 원화가) — 해외 전용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시 (서버 입력 기준)'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['trading.account_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_snapshot', schema='trading')
    op.drop_table('account_snapshot', schema='trading')
    # ### end Alembic commands ###
