"""add kis_news

Revision ID: 158bebdd9894
Revises: 305a8c2403c4
Create Date: 2025-10-16 11:10:46.621442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '158bebdd9894'
down_revision: Union[str, Sequence[str], None] = '305a8c2403c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='KIS 뉴스 ID'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='해외/국내 구분'),
    sa.Column('source_key', sa.Text(), nullable=False, comment='해외: news_key, 국내: cntt_usiq_srno'),
    sa.Column('ticker_id', sa.BigInteger(), nullable=False, comment='티커 ID'),
    sa.Column('title', sa.Text(), nullable=False, comment='뉴스 제목'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='발행 시간 (KST 기준)'),
    sa.Column('publisher', sa.Text(), nullable=True, comment='source(해외) / dorg(국내)'),
    sa.Column('class_cd', sa.Text(), nullable=True, comment='class_cd(해외) / news_lrdv_code(국내)'),
    sa.Column('class_name', sa.Text(), nullable=True, comment='class_name(해외)'),
    sa.Column('nation_cd', sa.Text(), nullable=True, comment='해외 nation_cd'),
    sa.Column('exchange_cd', sa.Text(), nullable=True, comment='해외 exchange_cd'),
    sa.Column('symbol', sa.Text(), nullable=True, comment='해외 symb (예: NVDA)'),
    sa.Column('symbol_name', sa.Text(), nullable=True, comment='해외 symb_name 한글명'),
    sa.Column('kr_iscd', sa.Text(), nullable=True, comment='국내 iscd1 (6자리 종목코드)'),
    sa.Column('lang', sa.String(length=10), nullable=True, comment='언어 코드'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='원문 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.CheckConstraint("source_type IN ('overseas', 'domestic')", name='ck_kis_news_source_type'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_kis_news_ticker_published', 'kis_news', ['ticker_id', 'published_at'], unique=False, schema='trading')
    op.create_index('ux_kis_news_source', 'kis_news', ['source_type', 'source_key'], unique=True, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ux_kis_news_source', table_name='kis_news', schema='trading')
    op.drop_index('ix_kis_news_ticker_published', table_name='kis_news', schema='trading')
    op.drop_table('kis_news', schema='trading')
    # ### end Alembic commands ###
