"""add news_anchor_v3

Revision ID: 16c64812ee6d
Revises: c01c7499f6cc
Create Date: 2025-10-08 21:51:58.878389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16c64812ee6d'
down_revision: Union[str, Sequence[str], None] = 'c01c7499f6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_anchor_vector', sa.Column('anchor_text', sa.Text(), nullable=False, comment='앵커 문장 (임베딩 생성용)'), schema='trading')
    op.drop_column('news_anchor_vector', 'keywords', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_anchor_vector', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='임베딩용 키워드 세트'), schema='trading')
    op.drop_column('news_anchor_vector', 'anchor_text', schema='trading')
    # ### end Alembic commands ###
