"""add_ticker_id_to_kis_position_execbasis

Revision ID: 17257a5e66eb
Revises: ee2d2d1c1472
Create Date: 2025-10-02 03:56:10.829982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17257a5e66eb'
down_revision: Union[str, Sequence[str], None] = 'ee2d2d1c1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kis_position_execbasis', sa.Column('ticker_id', sa.Integer(), nullable=True, comment='티커 ID (핀헙 기반)'), schema='trading')
    op.create_foreign_key(None, 'kis_position_execbasis', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kis_position_execbasis', schema='trading', type_='foreignkey')
    op.drop_column('kis_position_execbasis', 'ticker_id', schema='trading')
    # ### end Alembic commands ###
