"""add yf_macro v2

Revision ID: 1ae400988501
Revises: 95a560f6957d
Create Date: 2025-10-18 02:54:08.031618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae400988501'
down_revision: Union[str, Sequence[str], None] = '95a560f6957d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yahoo_index_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='시리즈 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='심볼 코드 (예: ^GSPC, ^KS11, KRW=X)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='지수/환율 이름'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='데이터 제공자 (yahoo_finance)'),
    sa.Column('freq', sa.String(length=20), nullable=True, comment='데이터 빈도 (daily)'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='단위'),
    sa.Column('active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_yahoo_series_code'),
    schema='trading'
    )
    op.create_table('yahoo_index_timeseries',
    sa.Column('series_id', sa.Integer(), nullable=False, comment='시리즈 ID (yahoo_index_series.id)'),
    sa.Column('d', sa.Date(), nullable=False, comment='날짜'),
    sa.Column('v', sa.Numeric(precision=20, scale=8), nullable=True, comment='값 (종가 또는 환율)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.ForeignKeyConstraint(['series_id'], ['trading.yahoo_index_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'd'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_yahoo_index_timeseries_d'), 'yahoo_index_timeseries', ['d'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_yahoo_index_timeseries_series_id'), 'yahoo_index_timeseries', ['series_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_yahoo_index_timeseries_series_id'), table_name='yahoo_index_timeseries', schema='trading')
    op.drop_index(op.f('ix_trading_yahoo_index_timeseries_d'), table_name='yahoo_index_timeseries', schema='trading')
    op.drop_table('yahoo_index_timeseries', schema='trading')
    op.drop_table('yahoo_index_series', schema='trading')
    # ### end Alembic commands ###
