"""add earnings_event

Revision ID: 269749ed9eaa
Revises: 8b8af18def16
Create Date: 2025-09-17 18:35:13.365564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269749ed9eaa'
down_revision: Union[str, Sequence[str], None] = '8b8af18def16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('estimate_eps', sa.Float(), nullable=True),
    sa.Column('actual_eps', sa.Float(), nullable=True),
    sa.Column('surprise_eps', sa.Float(), nullable=True),
    sa.Column('estimate_revenue', sa.Float(), nullable=True),
    sa.Column('actual_revenue', sa.Float(), nullable=True),
    sa.Column('surprise_revenue', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_symbol', 'report_date', name='uq_ticker_reportdate'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_earnings_event_report_date'), 'earnings_event', ['report_date'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_earnings_event_ticker_symbol'), 'earnings_event', ['ticker_symbol'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_earnings_event_ticker_symbol'), table_name='earnings_event', schema='trading')
    op.drop_index(op.f('ix_trading_earnings_event_report_date'), table_name='earnings_event', schema='trading')
    op.drop_table('earnings_event', schema='trading')
    # ### end Alembic commands ###
