"""add enum_v2

Revision ID: 28bfd1b48d3c
Revises: d4a8df41d878
Create Date: 2025-09-19 02:44:23.502383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28bfd1b48d3c'
down_revision: Union[str, Sequence[str], None] = 'd4a8df41d878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'status',
               existing_type=postgresql.ENUM('RAW', 'FILTERED', 'ANALYZED', name='newsstatus'),
               type_=sa.Enum('RAW', 'FILTERED_POSITIVE', 'FILTERED_NEGATIVE', 'ANALYZED', name='newsstatus', schema='trading'),
               existing_nullable=False,
               schema='trading')
    op.alter_column('news', 'content_status',
               existing_type=postgresql.ENUM('NONE', 'SUCCESS', 'FAILED_ONCE', 'FAILED_FINAL', name='contentstatus'),
               type_=sa.Enum('NONE', 'SUCCESS', 'FAILED_FINAL', name='contentstatus', schema='trading'),
               existing_nullable=False,
               schema='trading')
    op.drop_constraint(op.f('fk_news_ticker_ticker_id'), 'news_ticker', schema='trading', type_='foreignkey')
    op.create_foreign_key(None, 'news_ticker', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    op.create_index(op.f('ix_trading_ticker_exchange'), 'ticker', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_ticker_id'), 'ticker', ['id'], unique=False, schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    op.drop_constraint(op.f('fk_ticker_i18n_ticker_id'), 'ticker_i18n', schema='trading', type_='foreignkey')
    op.create_foreign_key(None, 'ticker_i18n', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    op.alter_column('ticker_industry', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='trading')
    op.drop_constraint(op.f('ticker_industry_industry_id_fkey'), 'ticker_industry', schema='trading', type_='foreignkey')
    op.drop_constraint(op.f('fk_ticker_industry_ticker_id'), 'ticker_industry', schema='trading', type_='foreignkey')
    op.create_foreign_key(None, 'ticker_industry', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    op.create_foreign_key(None, 'ticker_industry', 'industry', ['industry_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_ticker_theme_ticker_id'), 'ticker_theme', schema='trading', type_='foreignkey')
    op.drop_constraint(op.f('ticker_theme_theme_id_fkey'), 'ticker_theme', schema='trading', type_='foreignkey')
    op.create_foreign_key(None, 'ticker_theme', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    op.create_foreign_key(None, 'ticker_theme', 'theme', ['theme_id'], ['id'], source_schema='trading', referent_schema='trading', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticker_theme', schema='trading', type_='foreignkey')
    op.drop_constraint(None, 'ticker_theme', schema='trading', type_='foreignkey')
    op.create_foreign_key(op.f('ticker_theme_theme_id_fkey'), 'ticker_theme', 'theme', ['theme_id'], ['id'], source_schema='trading', referent_schema='trading')
    op.create_foreign_key(op.f('fk_ticker_theme_ticker_id'), 'ticker_theme', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading')
    op.drop_constraint(None, 'ticker_industry', schema='trading', type_='foreignkey')
    op.drop_constraint(None, 'ticker_industry', schema='trading', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticker_industry_ticker_id'), 'ticker_industry', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading')
    op.create_foreign_key(op.f('ticker_industry_industry_id_fkey'), 'ticker_industry', 'industry', ['industry_id'], ['id'], source_schema='trading', referent_schema='trading')
    op.alter_column('ticker_industry', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='trading')
    op.drop_constraint(None, 'ticker_i18n', schema='trading', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticker_i18n_ticker_id'), 'ticker_i18n', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading')
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.drop_index(op.f('ix_trading_ticker_id'), table_name='ticker', schema='trading')
    op.drop_index(op.f('ix_trading_ticker_exchange'), table_name='ticker', schema='trading')
    op.drop_constraint(None, 'news_ticker', schema='trading', type_='foreignkey')
    op.create_foreign_key(op.f('fk_news_ticker_ticker_id'), 'news_ticker', 'ticker', ['ticker_id'], ['id'], source_schema='trading', referent_schema='trading')
    op.alter_column('news', 'content_status',
               existing_type=sa.Enum('NONE', 'SUCCESS', 'FAILED_FINAL', name='contentstatus', schema='trading'),
               type_=postgresql.ENUM('NONE', 'SUCCESS', 'FAILED_ONCE', 'FAILED_FINAL', name='contentstatus'),
               existing_nullable=False,
               schema='trading')
    op.alter_column('news', 'status',
               existing_type=sa.Enum('RAW', 'FILTERED_POSITIVE', 'FILTERED_NEGATIVE', 'ANALYZED', name='newsstatus', schema='trading'),
               type_=postgresql.ENUM('RAW', 'FILTERED', 'ANALYZED', name='newsstatus'),
               existing_nullable=False,
               schema='trading')
    # ### end Alembic commands ###
