"""add earnings_event_v3

Revision ID: 29d2b24e7565
Revises: 4c8694911ed0
Create Date: 2025-09-17 23:48:52.163157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29d2b24e7565'
down_revision: Union[str, Sequence[str], None] = '4c8694911ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_event', sa.Column('period_end_date', sa.Date(), nullable=True), schema='trading')
    op.alter_column('earnings_event', 'fiscal_year',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='trading')
    op.alter_column('earnings_event', 'fiscal_quarter',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='trading')
    op.alter_column('earnings_event', 'report_date',
               existing_type=sa.DATE(),
               nullable=True,
               schema='trading')
    op.alter_column('earnings_event', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='trading')
    op.alter_column('earnings_event', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='trading')
    op.drop_index(op.f('ix_trading_earnings_event_report_date'), table_name='earnings_event', schema='trading')
    op.drop_constraint(op.f('uq_ticker_reportdate'), 'earnings_event', schema='trading', type_='unique')
    op.create_unique_constraint('uq_ticker_year_quarter', 'earnings_event', ['ticker_symbol', 'fiscal_year', 'fiscal_quarter'], schema='trading')
    op.drop_column('earnings_event', 'surprise_revenue', schema='trading')
    op.drop_column('earnings_event', 'last_updated_at', schema='trading')
    op.drop_column('earnings_event', 'ingested_at', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_event', sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True), schema='trading')
    op.add_column('earnings_event', sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='trading')
    op.add_column('earnings_event', sa.Column('surprise_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='trading')
    op.drop_constraint('uq_ticker_year_quarter', 'earnings_event', schema='trading', type_='unique')
    op.create_unique_constraint(op.f('uq_ticker_reportdate'), 'earnings_event', ['ticker_symbol', 'report_date'], schema='trading', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trading_earnings_event_report_date'), 'earnings_event', ['report_date'], unique=False, schema='trading')
    op.alter_column('earnings_event', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='trading')
    op.alter_column('earnings_event', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='trading')
    op.alter_column('earnings_event', 'report_date',
               existing_type=sa.DATE(),
               nullable=False,
               schema='trading')
    op.alter_column('earnings_event', 'fiscal_quarter',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='trading')
    op.alter_column('earnings_event', 'fiscal_year',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='trading')
    op.drop_column('earnings_event', 'period_end_date', schema='trading')
    # ### end Alembic commands ###
