"""add simil v6

Revision ID: 305a8c2403c4
Revises: ef5fa180d97d
Create Date: 2025-10-14 04:10:54.743539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305a8c2403c4'
down_revision: Union[str, Sequence[str], None] = 'ef5fa180d97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarity_analysis', sa.Column('exchange', sa.String(length=50), nullable=True, comment='거래소 코드'), schema='trading')
    op.drop_index(op.f('ix_trading_similarity_analysis_ticker_id'), table_name='similarity_analysis', schema='trading')
    op.drop_constraint(op.f('uq_similarity_ticker'), 'similarity_analysis', schema='trading', type_='unique')
    op.drop_column('similarity_analysis', 'created_at', schema='trading')
    op.drop_column('similarity_analysis', 'analysis_id', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarity_analysis', sa.Column('analysis_id', sa.BIGINT(), autoincrement=True, nullable=False, comment='분석 ID'), schema='trading')
    op.add_column('similarity_analysis', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='생성일시'), schema='trading')
    op.create_unique_constraint(op.f('uq_similarity_ticker'), 'similarity_analysis', ['ticker_id'], schema='trading', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trading_similarity_analysis_ticker_id'), 'similarity_analysis', ['ticker_id'], unique=True, schema='trading')
    op.drop_column('similarity_analysis', 'exchange', schema='trading')
    # ### end Alembic commands ###
