"""add unique constraint on dividend_history (ticker_id, payment_date)

Revision ID: 3889581f9dc7
Revises: b6416d841d03
Create Date: 2025-09-30 20:55:34.236924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3889581f9dc7'
down_revision: Union[str, Sequence[str], None] = 'b6416d841d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='추천 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID'),
    sa.Column('position_type', postgresql.ENUM('LONG', 'SHORT', name='positiontype', create_type=False, schema='trading'), nullable=False, comment='포지션 타입 (LONG/SHORT)'),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='진입가'),
    sa.Column('target_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='목표가'),
    sa.Column('stop_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='손절가'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False, comment='유효기간'),
    sa.Column('reason', sa.Text(), nullable=False, comment='추천 이유'),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False, comment='신뢰도 (0.00~1.00)'),
    sa.Column('recommended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='추천일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.CheckConstraint('confidence_score >= 0.00 AND confidence_score <= 1.00', name='ck_confidence_score_range'),
    sa.CheckConstraint('entry_price > 0', name='ck_entry_price_positive'),
    sa.CheckConstraint('stop_price IS NULL OR stop_price > 0', name='ck_stop_price_positive'),
    sa.CheckConstraint('target_price > 0', name='ck_target_price_positive'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('idx_analyst_recommendation_valid_until', 'analyst_recommendation', ['valid_until'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_analyst_recommendation_recommended_at'), 'analyst_recommendation', ['recommended_at'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_analyst_recommendation_ticker_id'), 'analyst_recommendation', ['ticker_id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_analyst_recommendation_valid_until'), 'analyst_recommendation', ['valid_until'], unique=False, schema='trading')
    op.create_unique_constraint('uq_dividend_history_ticker_date', 'dividend_history', ['ticker_id', 'payment_date'], schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dividend_history_ticker_date', 'dividend_history', schema='trading', type_='unique')
    op.drop_index(op.f('ix_trading_analyst_recommendation_valid_until'), table_name='analyst_recommendation', schema='trading')
    op.drop_index(op.f('ix_trading_analyst_recommendation_ticker_id'), table_name='analyst_recommendation', schema='trading')
    op.drop_index(op.f('ix_trading_analyst_recommendation_recommended_at'), table_name='analyst_recommendation', schema='trading')
    op.drop_index('idx_analyst_recommendation_valid_until', table_name='analyst_recommendation', schema='trading')
    op.drop_table('analyst_recommendation', schema='trading')
    # ### end Alembic commands ###
