"""add earnings_event_v2

Revision ID: 4c8694911ed0
Revises: 269749ed9eaa
Create Date: 2025-09-17 18:56:02.114410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8694911ed0'
down_revision: Union[str, Sequence[str], None] = '269749ed9eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_event', sa.Column('report_time', sa.String(length=20), nullable=True), schema='trading')
    op.add_column('earnings_event', sa.Column('status', sa.String(length=20), nullable=False), schema='trading')
    op.add_column('earnings_event', sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True), schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_event', 'last_updated_at', schema='trading')
    op.drop_column('earnings_event', 'status', schema='trading')
    op.drop_column('earnings_event', 'report_time', schema='trading')
    # ### end Alembic commands ###
