"""remove_unused_fields_from_order_plan

Revision ID: 4d48766ca42d
Revises: 792b9e7fa4a1
Create Date: 2025-10-02 23:44:06.017530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d48766ca42d'
down_revision: Union[str, Sequence[str], None] = '792b9e7fa4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_plan', 'risk_target', schema='trading')
    op.drop_column('order_plan', 'risk_entry', schema='trading')
    op.drop_column('order_plan', 'risk_stop', schema='trading')
    op.drop_column('order_plan', 'exchange', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_plan', sa.Column('exchange', sa.TEXT(), autoincrement=False, nullable=True, comment='거래소(선택, 예: NMS)'), schema='trading')
    op.add_column('order_plan', sa.Column('risk_stop', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True, comment='레퍼런스 스톱'), schema='trading')
    op.add_column('order_plan', sa.Column('risk_entry', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True, comment='레퍼런스 엔트리'), schema='trading')
    op.add_column('order_plan', sa.Column('risk_target', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True, comment='레퍼런스 타겟'), schema='trading')
    # ### end Alembic commands ###
