"""update_dividend_history_for_yfinance

Revision ID: 5a6a7b2f796f
Revises: ea4b73b15365
Create Date: 2025-09-28 07:09:59.821484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6a7b2f796f'
down_revision: Union[str, Sequence[str], None] = 'ea4b73b15365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividend_history', sa.Column('currency', sa.String(length=3), nullable=False, comment='통화 코드'), schema='trading')
    op.alter_column('dividend_history', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False,
               comment='배당 지급일',
               existing_comment='지급일',
               schema='trading')
    op.drop_column('dividend_history', 'ex_dividend_date', schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False, comment='티커 심볼'), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.add_column('dividend_history', sa.Column('ex_dividend_date', sa.DATE(), autoincrement=False, nullable=False, comment='배당락일'), schema='trading')
    op.alter_column('dividend_history', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True,
               comment='지급일',
               existing_comment='배당 지급일',
               schema='trading')
    op.drop_column('dividend_history', 'currency', schema='trading')
    # ### end Alembic commands ###
