"""add market

Revision ID: 5fc89434bc66
Revises: 85ad8d51f289
Create Date: 2025-09-26 02:05:02.330241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc89434bc66'
down_revision: Union[str, Sequence[str], None] = '85ad8d51f289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_symbol', sa.String(length=32), nullable=True),
    sa.Column('source_exchange', sa.String(length=16), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'trade_date', name='uq_ohlcv_daily_ticker_date'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_ohlcv_daily_ticker_id'), 'ohlcv_daily', ['ticker_id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_ohlcv_daily_trade_date'), 'ohlcv_daily', ['trade_date'], unique=False, schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.drop_index(op.f('ix_trading_ohlcv_daily_trade_date'), table_name='ohlcv_daily', schema='trading')
    op.drop_index(op.f('ix_trading_ohlcv_daily_ticker_id'), table_name='ohlcv_daily', schema='trading')
    op.drop_table('ohlcv_daily', schema='trading')
    # ### end Alembic commands ###
