"""add ticker_vector_v2

Revision ID: 672bff21f279
Revises: 26b7ee39f9b4
Create Date: 2025-10-09 00:04:14.047438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '672bff21f279'
down_revision: Union[str, Sequence[str], None] = '26b7ee39f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_vector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='티커 벡터 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='임베딩 모델명'),
    sa.Column('vector_dimension', sa.Integer(), nullable=False, comment='벡터 차원수'),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=False, comment='임베딩 벡터 배열'),
    sa.Column('source_text', sa.Text(), nullable=False, comment='임베딩 생성용 소스 텍스트'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='원본 텍스트 길이 (문자 수)'),
    sa.Column('token_length', sa.Integer(), nullable=True, comment='원본 텍스트 토큰 수 (자르기 전)'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='처리 시간 (밀리초)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'model_name', name='uq_ticker_vector_ticker_model'),
    schema='trading'
    )
    op.create_index('ix_ticker_vector_created_at', 'ticker_vector', ['created_at'], unique=False, schema='trading')
    op.create_index('ix_ticker_vector_model_name', 'ticker_vector', ['model_name'], unique=False, schema='trading')
    op.create_index('ix_ticker_vector_ticker_id', 'ticker_vector', ['ticker_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_vector_ticker_id', table_name='ticker_vector', schema='trading')
    op.drop_index('ix_ticker_vector_model_name', table_name='ticker_vector', schema='trading')
    op.drop_index('ix_ticker_vector_created_at', table_name='ticker_vector', schema='trading')
    op.drop_table('ticker_vector', schema='trading')
    # ### end Alembic commands ###
