"""add simil v2

Revision ID: 6f7fc27e2699
Revises: fa5b928617aa
Create Date: 2025-10-14 02:52:35.775572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7fc27e2699'
down_revision: Union[str, Sequence[str], None] = 'fa5b928617aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity_analysis',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='분석 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID (ticker 테이블 참조)'),
    sa.Column('ticker_name_ko', sa.String(length=255), nullable=True, comment='종목명 (한글)'),
    sa.Column('p_up', sa.Numeric(precision=10, scale=6), nullable=False, comment='상승 확률 (가중치 합)'),
    sa.Column('p_down', sa.Numeric(precision=10, scale=6), nullable=False, comment='하락 확률 (가중치 합)'),
    sa.Column('exp_up', sa.Numeric(precision=10, scale=6), nullable=False, comment='상승 시 기대 변동률'),
    sa.Column('exp_down', sa.Numeric(precision=10, scale=6), nullable=False, comment='하락 시 기대 변동률'),
    sa.Column('top_similarity', sa.Numeric(precision=10, scale=6), nullable=False, server_default='0', comment='가장 높은 유사도 점수 (TOP 1)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('ticker_id', name='uq_similarity_ticker'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_similarity_analysis_ticker_id'), 'similarity_analysis', ['ticker_id'], unique=True, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_similarity_analysis_ticker_id'), table_name='similarity_analysis', schema='trading')
    op.drop_table('similarity_analysis', schema='trading')
    # ### end Alembic commands ###
