"""add intra_signals_v2

Revision ID: 71ee803807d3
Revises: d49a2e489611
Create Date: 2025-10-12 17:06:55.945945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ee803807d3'
down_revision: Union[str, Sequence[str], None] = 'd49a2e489611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intraday_signal_detection_result', 'change_7_24d',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=14, scale=6),
               existing_comment='이후 7~24 캔들 변동률',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'past_slope',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=14, scale=6),
               existing_comment='직전 구간 기울기',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'past_std',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=14, scale=6),
               existing_comment='직전 구간 표준편차',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'atr',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=14, scale=6),
               existing_comment='평균 변동성 (ATR)',
               existing_nullable=True,
               schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intraday_signal_detection_result', 'atr',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_comment='평균 변동성 (ATR)',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'past_std',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_comment='직전 구간 표준편차',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'past_slope',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_comment='직전 구간 기울기',
               existing_nullable=True,
               schema='trading')
    op.alter_column('intraday_signal_detection_result', 'change_7_24d',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_comment='이후 7~24 캔들 변동률',
               existing_nullable=True,
               schema='trading')
    # ### end Alembic commands ###
