"""order_batch

Revision ID: 792b9e7fa4a1
Revises: 33fc625ca0b7
Create Date: 2025-10-02 21:06:14.290962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '792b9e7fa4a1'
down_revision: Union[str, Sequence[str], None] = '33fc625ca0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='배치ID'),
    sa.Column('asof_kst', sa.DateTime(timezone=True), nullable=False, comment='생성시각(KST)'),
    sa.Column('mode', sa.Text(), nullable=False, comment='배치구분(BUY/SELL)'),
    sa.Column('currency', sa.Text(), nullable=False, comment='계좌통화(예: USD)'),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=2), nullable=False, comment='가용현금(참고값)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='설계 메모(간단 코멘트)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.CheckConstraint("mode IN ('BUY','SELL')", name='ck_order_batch_mode'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('order_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='계획ID'),
    sa.Column('batch_id', sa.Integer(), nullable=False, comment='배치ID(FK)'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커ID'),
    sa.Column('symbol', sa.Text(), nullable=False, comment='심볼(예: MSFT)'),
    sa.Column('exchange', sa.Text(), nullable=True, comment='거래소(선택, 예: NMS)'),
    sa.Column('action', sa.Text(), nullable=False, comment='액션(BUY/SELL)'),
    sa.Column('recommendation_id', sa.Integer(), nullable=True, comment='추천서ID(참고)'),
    sa.Column('note', sa.Text(), nullable=True, comment='사유(2줄 이내 요약)'),
    sa.Column('risk_entry', sa.Numeric(precision=20, scale=4), nullable=True, comment='레퍼런스 엔트리'),
    sa.Column('risk_target', sa.Numeric(precision=20, scale=4), nullable=True, comment='레퍼런스 타겟'),
    sa.Column('risk_stop', sa.Numeric(precision=20, scale=4), nullable=True, comment='레퍼런스 스톱'),
    sa.Column('decision', sa.Text(), nullable=False, comment='실행/제외'),
    sa.Column('skip_code', sa.Text(), nullable=True, comment='제외코드'),
    sa.Column('skip_note', sa.Text(), nullable=True, comment='제외사유'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.CheckConstraint("action IN ('BUY','SELL')", name='ck_order_plan_action'),
    sa.CheckConstraint("decision IN ('EXECUTE','SKIP')", name='ck_order_plan_decision'),
    sa.CheckConstraint("skip_code IN ('HOLD','CASH','EXPIRED','RISK','DUPLICATE','SPREAD','OTHER')", name='ck_order_plan_skip_code'),
    sa.ForeignKeyConstraint(['batch_id'], ['trading.order_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_order_plan_batch_id', 'order_plan', ['batch_id'], unique=False, schema='trading')
    op.create_index('ix_order_plan_ticker_id', 'order_plan', ['ticker_id'], unique=False, schema='trading')
    op.create_index('uq_order_plan_batch_symbol_action', 'order_plan', ['batch_id', 'symbol', 'action'], unique=True, schema='trading', postgresql_where=sa.text("decision = 'EXECUTE'"))
    op.create_table('order_leg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='레그ID'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='계획ID(FK)'),
    sa.Column('type', sa.Text(), nullable=False, comment='주문유형'),
    sa.Column('side', sa.Text(), nullable=False, comment='매수/매도'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='수량(정수, 1주단위)'),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='가격(LIMIT/LOC일 때)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_order_leg_side'),
    sa.CheckConstraint("type IN ('LIMIT','MARKET','LOC')", name='ck_order_leg_type'),
    sa.CheckConstraint('quantity > 0', name='ck_order_leg_quantity_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['trading.order_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_order_leg_plan_id', 'order_leg', ['plan_id'], unique=False, schema='trading')
    op.create_table('broker_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='브로커주문ID'),
    sa.Column('leg_id', sa.Integer(), nullable=False, comment='레그ID(FK)'),
    sa.Column('broker_order_uid', sa.Text(), nullable=True, comment='브로커주문고유ID'),
    sa.Column('ord_dvsn', sa.Text(), nullable=False, comment='브로커 주문구분(00/34 등)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='전송페이로드 스냅샷'),
    sa.Column('status', sa.Text(), nullable=False, comment='상태'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='전송시각'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='완료시각'),
    sa.Column('reject_code', sa.Text(), nullable=True, comment='거절코드'),
    sa.Column('reject_message', sa.Text(), nullable=True, comment='거절사유'),
    sa.CheckConstraint("status IN ('SUBMITTED','ACCEPTED','PARTIAL','FILLED','CANCELLED','REJECTED')", name='ck_broker_order_status'),
    sa.ForeignKeyConstraint(['leg_id'], ['trading.order_leg.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_broker_order_broker_order_uid', 'broker_order', ['broker_order_uid'], unique=False, schema='trading')
    op.create_index('ix_broker_order_leg_id', 'broker_order', ['leg_id'], unique=False, schema='trading')
    op.create_table('order_fill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='체결ID'),
    sa.Column('broker_order_id', sa.Integer(), nullable=False, comment='브로커주문ID(FK)'),
    sa.Column('fill_qty', sa.Integer(), nullable=False, comment='체결수량'),
    sa.Column('fill_price', sa.Numeric(precision=20, scale=4), nullable=False, comment='체결가격'),
    sa.Column('fee', sa.Numeric(precision=20, scale=4), nullable=True, comment='수수료'),
    sa.Column('liquidity_flag', sa.Text(), nullable=True, comment='유동성플래그(maker/taker 등)'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False, comment='체결시각'),
    sa.CheckConstraint('fill_qty > 0', name='ck_order_fill_qty_positive'),
    sa.ForeignKeyConstraint(['broker_order_id'], ['trading.broker_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_order_fill_broker_order_id', 'order_fill', ['broker_order_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_fill_broker_order_id', table_name='order_fill', schema='trading')
    op.drop_table('order_fill', schema='trading')
    op.drop_index('ix_broker_order_leg_id', table_name='broker_order', schema='trading')
    op.drop_index('ix_broker_order_broker_order_uid', table_name='broker_order', schema='trading')
    op.drop_table('broker_order', schema='trading')
    op.drop_index('ix_order_leg_plan_id', table_name='order_leg', schema='trading')
    op.drop_table('order_leg', schema='trading')
    op.drop_index('uq_order_plan_batch_symbol_action', table_name='order_plan', schema='trading', postgresql_where=sa.text("decision = 'EXECUTE'"))
    op.drop_index('ix_order_plan_ticker_id', table_name='order_plan', schema='trading')
    op.drop_index('ix_order_plan_batch_id', table_name='order_plan', schema='trading')
    op.drop_table('order_plan', schema='trading')
    op.drop_table('order_batch', schema='trading')
    # ### end Alembic commands ###
