"""add sector

Revision ID: 7d3b1ca9b99b
Revises: 8f0e913d2c18
Create Date: 2025-09-16 20:57:56.851723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3b1ca9b99b'
down_revision: Union[str, Sequence[str], None] = '8f0e913d2c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='trading'
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['trading.sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('sector_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['trading.sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('industry_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['trading.industry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('ticker_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['trading.industry.id'], ),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.drop_index(op.f('ix_trading_ticker_category_id'), table_name='ticker_category', schema='trading')
    op.drop_table('ticker_category', schema='trading')
    op.drop_index(op.f('ix_trading_category_i18n_id'), table_name='category_i18n', schema='trading')
    op.drop_table('category_i18n', schema='trading')
    op.drop_index(op.f('ix_trading_category_id'), table_name='category', schema='trading')
    op.drop_table('category', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trading.category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('system', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    schema='trading',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_trading_category_id'), 'category', ['id'], unique=False, schema='trading')
    op.create_table('category_i18n',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lang_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['trading.category.id'], name=op.f('category_i18n_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('category_i18n_pkey')),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_category_i18n_id'), 'category_i18n', ['id'], unique=False, schema='trading')
    op.create_table('ticker_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['trading.category.id'], name=op.f('ticker_category_category_id_fkey')),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], name=op.f('ticker_category_ticker_symbol_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticker_category_pkey')),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_ticker_category_id'), 'ticker_category', ['id'], unique=False, schema='trading')
    op.drop_table('ticker_industry', schema='trading')
    op.drop_table('industry_i18n', schema='trading')
    op.drop_table('sector_i18n', schema='trading')
    op.drop_table('industry', schema='trading')
    op.drop_table('sector', schema='trading')
    # ### end Alembic commands ###
