"""add news_anchor_v5

Revision ID: 801fe9c1f35d
Revises: 7ad8d2e458ef
Create Date: 2025-10-08 22:40:18.974339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801fe9c1f35d'
down_revision: Union[str, Sequence[str], None] = '7ad8d2e458ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_vector', sa.Column('token_length', sa.Integer(), nullable=True, comment='원본 텍스트 토큰 수 (자르기 전)'), schema='trading')
    op.alter_column('news_vector', 'text_length',
               existing_type=sa.INTEGER(),
               comment='원본 텍스트 길이 (문자 수)',
               existing_comment='원본 텍스트 길이',
               existing_nullable=True,
               schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_vector', 'text_length',
               existing_type=sa.INTEGER(),
               comment='원본 텍스트 길이',
               existing_comment='원본 텍스트 길이 (문자 수)',
               existing_nullable=True,
               schema='trading')
    op.drop_column('news_vector', 'token_length', schema='trading')
    # ### end Alembic commands ###
