"""add fred v3

Revision ID: 85ad8d51f289
Revises: fbf1b21eb41d
Create Date: 2025-09-23 03:58:04.952514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ad8d51f289'
down_revision: Union[str, Sequence[str], None] = 'fbf1b21eb41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_release', schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.create_table('macro_release',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('event_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('importance', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('actual', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('consensus', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('previous', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('surprise', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_revised', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('macro_release_pkey')),
    sa.UniqueConstraint('source', 'event_code', 'event_time', name=op.f('uq_release_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='trading'
    )
    # ### end Alembic commands ###
