"""add sector v2

Revision ID: 8b8af18def16
Revises: 7d3b1ca9b99b
Create Date: 2025-09-16 21:02:54.583680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8af18def16'
down_revision: Union[str, Sequence[str], None] = '7d3b1ca9b99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_industry_code_sector', 'industry', ['code', 'sector_id'], schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_industry_code_sector', 'industry', schema='trading', type_='unique')
    # ### end Alembic commands ###
