"""add theme tables

Revision ID: 8f0e913d2c18
Revises: b40b6cfd3b53
Create Date: 2025-09-15 13:49:50.403313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0e913d2c18'
down_revision: Union[str, Sequence[str], None] = 'b40b6cfd3b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_theme_id'), 'theme', ['id'], unique=False, schema='trading')
    op.create_table('theme_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['trading.theme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_theme_i18n_id'), 'theme_i18n', ['id'], unique=False, schema='trading')
    op.create_table('ticker_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['trading.theme.id'], ),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_ticker_theme_id'), 'ticker_theme', ['id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_ticker_theme_id'), table_name='ticker_theme', schema='trading')
    op.drop_table('ticker_theme', schema='trading')
    op.drop_index(op.f('ix_trading_theme_i18n_id'), table_name='theme_i18n', schema='trading')
    op.drop_table('theme_i18n', schema='trading')
    op.drop_index(op.f('ix_trading_theme_id'), table_name='theme', schema='trading')
    op.drop_table('theme', schema='trading')
    # ### end Alembic commands ###
