"""add yf_macro

Revision ID: 95a560f6957d
Revises: 158bebdd9894
Create Date: 2025-10-18 02:49:49.979111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a560f6957d'
down_revision: Union[str, Sequence[str], None] = '158bebdd9894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### end Alembic commands ###
