"""fundmentaluq_fundamental_snapshot_ticker

Revision ID: 99dc77ac141d
Revises: 3889581f9dc7
Create Date: 2025-09-30 21:10:13.230795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99dc77ac141d'
down_revision: Union[str, Sequence[str], None] = '3889581f9dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_fundamental_snapshot_ticker', 'fundamental_snapshot', ['ticker_id'], schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fundamental_snapshot_ticker', 'fundamental_snapshot', schema='trading', type_='unique')
    # ### end Alembic commands ###
