"""rename korea_exchange_order_org_no to routing_org_code

Revision ID: 9c886d624e96
Revises: 0b5ed7204e68
Create Date: 2025-10-07 07:05:23.309175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c886d624e96'
down_revision: Union[str, Sequence[str], None] = '0b5ed7204e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_order', sa.Column('routing_org_code', sa.Text(), nullable=True, comment='거래소 전송 조직번호 (국내/해외 공용)'), schema='trading')
    op.drop_column('broker_order', 'korea_exchange_order_org_no', schema='trading')
    op.alter_column('fundamental_snapshot', 'market_cap',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='시가총액',
               existing_comment='시가총액 (달러:백만,한화:원)',
               existing_nullable=True,
               schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fundamental_snapshot', 'market_cap',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               comment='시가총액 (달러:백만,한화:원)',
               existing_comment='시가총액',
               existing_nullable=True,
               schema='trading')
    op.add_column('broker_order', sa.Column('korea_exchange_order_org_no', sa.TEXT(), autoincrement=False, nullable=True, comment='한국거래소전송주문조직번호'), schema='trading')
    op.drop_column('broker_order', 'routing_org_code', schema='trading')
    # ### end Alembic commands ###
