"""add gpt_log

Revision ID: a4c451299782
Revises: 28bfd1b48d3c
Create Date: 2025-09-22 03:24:52.273630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c451299782'
down_revision: Union[str, Sequence[str], None] = '28bfd1b48d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_news_summary_news_id', 'news_summary', ['news_id'], unique=False, schema='trading')
    op.create_unique_constraint('uq_news_summary_news_lang', 'news_summary', ['news_id', 'lang'], schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    #op.drop_constraint('uq_news_summary_news_lang', 'news_summary', schema='trading', type_='unique')
    op.drop_index('ix_news_summary_news_id', table_name='news_summary', schema='trading')
    # ### end Alembic commands ###
