"""add news_v3

Revision ID: a56b3d8daeb0
Revises: ded1bf26121f
Create Date: 2025-09-18 18:00:16.589512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56b3d8daeb0'
down_revision: Union[str, Sequence[str], None] = 'ded1bf26121f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('published_date_kst', sa.Date(), nullable=True), schema='trading')
    op.add_column('news', sa.Column('filter_score', sa.Float(), nullable=True), schema='trading')
    op.add_column('news', sa.Column('filter_model', sa.String(length=100), nullable=True), schema='trading')
    op.add_column('news', sa.Column('filter_attempts', sa.Integer(), nullable=False), schema='trading')
    op.add_column('news', sa.Column('content_retry_count', sa.Integer(), nullable=False), schema='trading')
    op.create_index('ix_news_published_date_kst', 'news', ['published_date_kst'], unique=False, schema='trading')
    op.add_column('news_summary', sa.Column('model', sa.String(length=100), nullable=True), schema='trading')
    op.add_column('news_theme', sa.Column('method', sa.String(length=50), nullable=True), schema='trading')
    op.create_unique_constraint('uq_news_theme__news_theme', 'news_theme', ['news_id', 'theme_id'], schema='trading')
    op.add_column('news_ticker', sa.Column('method', sa.String(length=50), nullable=True), schema='trading')
    op.add_column('news_ticker', sa.Column('candidate_pool_size', sa.Integer(), nullable=True), schema='trading')
    op.create_unique_constraint('uq_news_ticker__news_symbol', 'news_ticker', ['news_id', 'ticker_symbol'], schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_ticker__news_symbol', 'news_ticker', schema='trading', type_='unique')
    op.drop_column('news_ticker', 'candidate_pool_size', schema='trading')
    op.drop_column('news_ticker', 'method', schema='trading')
    op.drop_constraint('uq_news_theme__news_theme', 'news_theme', schema='trading', type_='unique')
    op.drop_column('news_theme', 'method', schema='trading')
    op.drop_column('news_summary', 'model', schema='trading')
    op.drop_index('ix_news_published_date_kst', table_name='news', schema='trading')
    op.drop_column('news', 'content_retry_count', schema='trading')
    op.drop_column('news', 'filter_attempts', schema='trading')
    op.drop_column('news', 'filter_model', schema='trading')
    op.drop_column('news', 'filter_score', schema='trading')
    op.drop_column('news', 'published_date_kst', schema='trading')
    # ### end Alembic commands ###
