"""trade_real

Revision ID: acef4bc4e4c8
Revises: ee3d4c11c244
Create Date: 2025-10-10 05:17:58.572587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acef4bc4e4c8'
down_revision: Union[str, Sequence[str], None] = 'ee3d4c11c244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_realized_pnl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='내부 PK (auto)'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='매매일자'),
    sa.Column('market_type', sa.String(length=10), nullable=False, comment="시장구분: 'KR' | 'US'"),
    sa.Column('exchange_code', sa.String(length=10), nullable=True, comment='거래소 코드 (e.g. KRX, NASDAQ)'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='종목코드 (e.g. 005930, AAPL)'),
    sa.Column('instrument_name', sa.Text(), nullable=False, comment='종목명'),
    sa.Column('currency_code', sa.String(length=10), nullable=False, comment='통화코드 (KRW, USD, etc.)'),
    sa.Column('buy_qty', sa.Numeric(precision=18, scale=4), nullable=True, comment='매수수량'),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=4), nullable=True, comment='매입단가'),
    sa.Column('buy_amount', sa.Numeric(precision=18, scale=4), nullable=True, comment='매수금액'),
    sa.Column('sell_qty', sa.Numeric(precision=18, scale=4), nullable=True, comment='매도수량'),
    sa.Column('sell_price', sa.Numeric(precision=18, scale=4), nullable=True, comment='매도가격'),
    sa.Column('sell_amount', sa.Numeric(precision=18, scale=4), nullable=True, comment='매도금액'),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False, comment='실현손익금액'),
    sa.Column('pnl_rate', sa.Numeric(precision=9, scale=4), nullable=True, comment='손익률 (%)'),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=True, comment='수수료'),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=True, comment='제세금'),
    sa.Column('interest', sa.Numeric(precision=18, scale=4), nullable=True, comment='대출이자 (국내만)'),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True, comment='환율 (해외만)'),
    sa.Column('note', sa.Text(), nullable=True, comment='비고 또는 원본 참조용'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_realized_pnl', schema='trading')
    # ### end Alembic commands ###
