"""add_analysis_price_to_analyst_recommendation

Revision ID: f1a2b3c4d5e6
Revises: ee2d2d1c1472
Create Date: 2025-01-27 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'ef41e080cabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyst_recommendation', sa.Column('analysis_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='분석 당시 최근가격'), schema='trading')
    op.create_check_constraint('ck_analysis_price_positive', 'analyst_recommendation', 'analysis_price IS NULL OR analysis_price > 0', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_analysis_price_positive', 'analyst_recommendation', type_='check', schema='trading')
    op.drop_column('analyst_recommendation', 'analysis_price', schema='trading')
    # ### end Alembic commands ###
