"""add_market_holidays_table

Revision ID: add_market_holidays_table
Revises: f54868c6b299
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_market_holidays_table'
down_revision = 'f54868c6b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_holiday',
    sa.Column('id', sa.Integer(), nullable=False, comment='휴일 ID'),
    sa.Column('exchange', sa.String(length=10), nullable=False, comment='거래소 코드 (예: US, KR, JP)'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='거래소 타임존 (예: America/New_York)'),
    sa.Column('at_date', sa.Date(), nullable=False, comment='휴일 날짜 (atDate)'),
    sa.Column('event_name', sa.String(length=100), nullable=False, comment='휴일명 (eventName)'),
    sa.Column('trading_hour', sa.String(length=20), nullable=True, comment='거래 시간 (tradingHour, 빈값이면 완전휴일)'),
    sa.Column('is_open', sa.Boolean(), nullable=False, comment='해당 날짜 거래소 개장 여부 (tradingHour 기반)'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_market_holiday_id'), 'market_holiday', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_exchange'), 'market_holiday', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_at_date'), 'market_holiday', ['at_date'], unique=False, schema='trading')
    op.create_unique_constraint('uq_market_holiday_exchange_date', 'market_holiday', ['exchange', 'at_date'], schema='trading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_holiday_exchange_date', 'market_holiday', type_='unique', schema='trading')
    op.drop_index(op.f('ix_market_holiday_at_date'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_exchange'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_id'), table_name='market_holiday', schema='trading')
    op.drop_table('market_holiday', schema='trading')
    # ### end Alembic commands ###
