"""add analyst_recommendation_table

Revision ID: add_analyst_recommendation_table
Revises: a56b3d8daeb0
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_analyst_recommendation_table'
down_revision: Union[str, Sequence[str], None] = 'd9dac394421f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('analyst_recommendation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='추천 ID'),
        sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID'),
        sa.Column('position_type', sa.Enum('LONG', 'SHORT', name='positiontype', schema='trading'), nullable=False, comment='포지션 타입 (LONG/SHORT)'),
        sa.Column('entry_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='진입가'),
        sa.Column('target_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='목표가'),
        sa.Column('stop_price', sa.Numeric(precision=15, scale=4), nullable=True, comment='손절가'),
        sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False, comment='유효기간'),
        sa.Column('reason', sa.Text(), nullable=False, comment='추천 이유'),
        sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False, comment='신뢰도 (0.00~1.00)'),
        sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='추천일시'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='생성일시'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='수정일시'),
        sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("confidence_score >= 0.00 AND confidence_score <= 1.00", name='ck_confidence_score_range'),
        sa.CheckConstraint("entry_price > 0", name='ck_entry_price_positive'),
        sa.CheckConstraint("target_price > 0", name='ck_target_price_positive'),
        sa.CheckConstraint("stop_price IS NULL OR stop_price > 0", name='ck_stop_price_positive'),
        schema='trading'
    )
    op.create_index('idx_analyst_recommendation_ticker_id', 'analyst_recommendation', ['ticker_id'], unique=False, schema='trading')
    op.create_index('idx_analyst_recommendation_recommended_at', 'analyst_recommendation', ['recommended_at'], unique=False, schema='trading')
    op.create_index('idx_analyst_recommendation_valid_until', 'analyst_recommendation', ['valid_until'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analyst_recommendation_valid_until', table_name='analyst_recommendation', schema='trading')
    op.drop_index('idx_analyst_recommendation_recommended_at', table_name='analyst_recommendation', schema='trading')
    op.drop_index('idx_analyst_recommendation_ticker_id', table_name='analyst_recommendation', schema='trading')
    op.drop_table('analyst_recommendation', schema='trading')
    # ### end Alembic commands ###
