"""add macro group tables

Revision ID: add_macro_group_tables
Revises: f06228edda61
Create Date: 2025-01-27 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_macro_group_tables'
down_revision: Union[str, Sequence[str], None] = 'f06228edda61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create macro_group table
    op.create_table('macro_group',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='매크로 그룹 ID'),
        sa.Column('code', sa.String(length=64), nullable=False, comment='그룹 코드 (예: INFLATION, LABOR)'),
        sa.Column('name', sa.String(length=128), nullable=False, comment='그룹 이름 (예: Inflation, Labor)'),
        sa.Column('description', sa.Text(), nullable=True, comment='그룹 설명'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='사용유무'),
        sa.Column('sort_order', sa.Integer(), nullable=True, comment='정렬 순서'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='생성일시'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='수정일시'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', name='uq_macro_group_code'),
        schema='trading'
    )
    
    # Create macro_group_series table
    op.create_table('macro_group_series',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='그룹-시리즈 관계 ID'),
        sa.Column('group_id', sa.Integer(), nullable=False, comment='그룹 ID'),
        sa.Column('series_id', sa.Integer(), nullable=False, comment='시리즈 ID'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='사용유무'),
        sa.Column('sort_order', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='그룹 내 정렬 순서'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='생성일시'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='수정일시'),
        sa.ForeignKeyConstraint(['group_id'], ['trading.macro_group.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['series_id'], ['trading.macro_data_series.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'series_id', name='uq_macro_group_series'),
        schema='trading'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_group_series', schema='trading')
    op.drop_table('macro_group', schema='trading')
    # ### end Alembic commands ###
