"""start

Revision ID: b40b6cfd3b53
Revises: 643e173775a4
Create Date: 2025-09-15 13:22:52.857173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40b6cfd3b53'
down_revision: Union[str, Sequence[str], None] = '643e173775a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('ticker',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    schema='trading'
    )
    op.create_table('category_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['trading.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('ticker_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['trading.category.id'], ),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('ticker_fundamentals',
    sa.Column('ticker_symbol', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('trailing_pe', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('trailing_eps', sa.Float(), nullable=True),
    sa.Column('price_to_book', sa.Float(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('profit_margins', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ),
    sa.PrimaryKeyConstraint('ticker_symbol'),
    schema='trading'
    )
    op.create_table('ticker_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_i18n', schema='trading')
    op.drop_table('ticker_fundamentals', schema='trading')
    op.drop_table('ticker_category', schema='trading')
    op.drop_table('category_i18n', schema='trading')
    op.drop_table('ticker', schema='trading')
    op.drop_table('category', schema='trading')
    # ### end Alembic commands ###
