"""remove_macro_ind

Revision ID: b6416d841d03
Revises: modify_market_holiday_table
Create Date: 2025-09-30 15:44:16.880432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6416d841d03'
down_revision: Union[str, Sequence[str], None] = 'modify_market_holiday_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_indicator_series', schema='trading')
    op.drop_index(op.f('idx_analyst_recommendation_recommended_at'), table_name='analyst_recommendation', schema='trading')
    op.drop_index(op.f('idx_analyst_recommendation_ticker_id'), table_name='analyst_recommendation', schema='trading')
    op.drop_index(op.f('idx_analyst_recommendation_valid_until'), table_name='analyst_recommendation', schema='trading')
    op.drop_table('analyst_recommendation', schema='trading')
    op.drop_table('macro_indicator', schema='trading')
    op.drop_index(op.f('ix_market_holiday_at_date'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_exchange'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_id'), table_name='market_holiday', schema='trading')
    op.create_index(op.f('ix_trading_market_holiday_at_date'), 'market_holiday', ['at_date'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_holiday_exchange'), 'market_holiday', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_holiday_id'), 'market_holiday', ['id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_market_holiday_id'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_trading_market_holiday_exchange'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_trading_market_holiday_at_date'), table_name='market_holiday', schema='trading')
    op.create_index(op.f('ix_market_holiday_id'), 'market_holiday', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_exchange'), 'market_holiday', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_at_date'), 'market_holiday', ['at_date'], unique=False, schema='trading')
    op.create_table('macro_indicator',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trading.macro_indicator_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='macro_indicator_pkey'),
    sa.UniqueConstraint('code', name='uq_macro_indicator_code', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='trading',
    postgresql_ignore_search_path=False
    )
    
    op.create_table('macro_indicator_series',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fred_series_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['trading.macro_indicator.id'], name=op.f('macro_indicator_series_indicator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('macro_indicator_series_pkey')),
    sa.UniqueConstraint('indicator_id', 'fred_series_id', name=op.f('uq_indicator_series'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='trading'
    )
    # ### end Alembic commands ###
