"""add_fundamentals_tables

Revision ID: bc77059171c7
Revises: 7717f15849df
Create Date: 2025-09-28 06:12:40.607877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc77059171c7'
down_revision: Union[str, Sequence[str], None] = '7717f15849df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False, comment='티커 심볼'), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    # ### end Alembic commands ###
