"""add news_anchor_v2

Revision ID: c01c7499f6cc
Revises: b4b1ee792a32
Create Date: 2025-10-08 21:19:49.310836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c01c7499f6cc'
down_revision: Union[str, Sequence[str], None] = 'b4b1ee792a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_anchor_vector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='앵커 벡터 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='앵커 코드 (예: MACRO, EARNINGS, POLICY)'),
    sa.Column('name_ko', sa.String(length=100), nullable=True, comment='한글명'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True, comment='임베딩용 키워드 세트'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='임베딩 모델명'),
    sa.Column('vector_dimension', sa.Integer(), nullable=False, comment='벡터 차원수'),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=False, comment='임베딩 벡터 배열'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_news_anchor_vector_code'),
    schema='trading'
    )
    op.create_index('ix_news_anchor_vector_code', 'news_anchor_vector', ['code'], unique=False, schema='trading')
    op.create_index('ix_news_anchor_vector_created_at', 'news_anchor_vector', ['created_at'], unique=False, schema='trading')
    op.create_index('ix_news_anchor_vector_model_name', 'news_anchor_vector', ['model_name'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_anchor_vector_model_name', table_name='news_anchor_vector', schema='trading')
    op.drop_index('ix_news_anchor_vector_created_at', table_name='news_anchor_vector', schema='trading')
    op.drop_index('ix_news_anchor_vector_code', table_name='news_anchor_vector', schema='trading')
    op.drop_table('news_anchor_vector', schema='trading')
    # ### end Alembic commands ###
