"""add kis

Revision ID: c1338b282ccd
Revises: 5fc89434bc66
Create Date: 2025-09-26 07:39:20.429490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1338b282ccd'
down_revision: Union[str, Sequence[str], None] = '5fc89434bc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    # ### end Alembic commands ###
