"""add news_vector

Revision ID: c658b25aed26
Revises: 7bf3e8c09459
Create Date: 2025-10-08 20:13:33.871627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c658b25aed26'
down_revision: Union[str, Sequence[str], None] = '7bf3e8c09459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_vector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='뉴스 벡터 ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='뉴스 ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='임베딩 모델명 (예: textembedding-gecko@003)'),
    sa.Column('vector_dimension', sa.Integer(), nullable=False, comment='벡터 차원수'),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=False, comment='임베딩 벡터 배열'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='원본 텍스트 길이'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='처리 시간 (밀리초)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='처리 상태 (SUCCESS, FAILED)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['news_id'], ['trading.news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'model_name', name='uq_news_vector_news_model'),
    schema='trading'
    )
    op.create_index('ix_news_vector_created_at', 'news_vector', ['created_at'], unique=False, schema='trading')
    op.create_index('ix_news_vector_model_name', 'news_vector', ['model_name'], unique=False, schema='trading')
    op.create_index('ix_news_vector_news_id', 'news_vector', ['news_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_vector_news_id', table_name='news_vector', schema='trading')
    op.drop_index('ix_news_vector_model_name', table_name='news_vector', schema='trading')
    op.drop_index('ix_news_vector_created_at', table_name='news_vector', schema='trading')
    op.drop_table('news_vector', schema='trading')
    # ### end Alembic commands ###
