"""add hybrid_trade

Revision ID: c8eb3fa17aa4
Revises: 71ee803807d3
Create Date: 2025-10-13 03:36:21.673167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8eb3fa17aa4'
down_revision: Union[str, Sequence[str], None] = '71ee803807d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_symbol_block',
    sa.Column('symbol', sa.Text(), nullable=False, comment='종목 심볼'),
    sa.Column('block_date', sa.Date(), nullable=False, comment='차단 일자'),
    sa.Column('reason', sa.Text(), nullable=True, comment='차단 사유 (realized_loss, snapshot_delta 등)'),
    sa.Column('pnl_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='손실률 (예: -0.0150 = -1.5%)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.PrimaryKeyConstraint('symbol', 'block_date'),
    schema='trading'
    )
    op.create_index('idx_daily_symbol_block_date', 'daily_symbol_block', ['block_date'], unique=False, schema='trading')
    op.create_table('leg_action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='액션 로그 ID'),
    sa.Column('leg_id', sa.Integer(), nullable=False, comment='레그 ID (FK)'),
    sa.Column('symbol', sa.Text(), nullable=True, comment='종목 심볼'),
    sa.Column('action', sa.Text(), nullable=False, comment='액션 타입 (REPRICE_UP, CANCEL, REPLACE, SUSPEND_DOWN_SIGNAL, NEAR_CLOSE_TRIM 등)'),
    sa.Column('note', sa.Text(), nullable=True, comment='액션 상세 내역'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['leg_id'], ['trading.order_leg.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('idx_leg_action_log_created_at', 'leg_action_log', ['created_at'], unique=False, schema='trading')
    op.create_index('idx_leg_action_log_leg_id', 'leg_action_log', ['leg_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leg_action_log_leg_id', table_name='leg_action_log', schema='trading')
    op.drop_index('idx_leg_action_log_created_at', table_name='leg_action_log', schema='trading')
    op.drop_table('leg_action_log', schema='trading')
    op.drop_index('idx_daily_symbol_block_date', table_name='daily_symbol_block', schema='trading')
    op.drop_table('daily_symbol_block', schema='trading')
    # ### end Alembic commands ###
