"""add intra_signals

Revision ID: d49a2e489611
Revises: edb6a32cceb1
Create Date: 2025-10-12 10:08:09.180990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49a2e489611'
down_revision: Union[str, Sequence[str], None] = 'edb6a32cceb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intraday_signal_detection_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False, comment='설정 ID'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='시그널 방향 (UP/DOWN)'),
    sa.Column('lookback', sa.Integer(), nullable=False, comment='직전 구간 확인 기간'),
    sa.Column('future_window', sa.Integer(), nullable=False, comment='이후 구간 평가 기간'),
    sa.Column('min_change', sa.Numeric(precision=6, scale=4), nullable=False, comment='최소 변동률'),
    sa.Column('max_reverse', sa.Numeric(precision=6, scale=4), nullable=False, comment='반대 방향 최대 허용폭'),
    sa.Column('flatness_k', sa.Numeric(precision=6, scale=4), nullable=False, comment='평탄성 허용치 (ATR 배수)'),
    sa.Column('atr_window', sa.Integer(), nullable=False, comment='ATR 계산 윈도우'),
    sa.Column('version', sa.String(length=10), nullable=False, comment='알고리즘 버전 (탐지+벡터)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.CheckConstraint("direction IN ('UP', 'DOWN')", name='ck_intraday_direction'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('direction', 'lookback', 'future_window', 'min_change', 'max_reverse', 'flatness_k', 'atr_window', 'version', name='uq_intraday_config_params'),
    schema='trading'
    )
    op.create_table('intraday_signal_detection_result',
    sa.Column('result_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='결과 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID (ticker 테이블 참조)'),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='설정 ID'),
    sa.Column('signal_datetime', sa.DateTime(), nullable=False, comment='시그널 발생 날짜+시간 (분 단위)'),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=True, comment='종가'),
    sa.Column('change_7_24d', sa.Numeric(precision=14, scale=6), nullable=True, comment='이후 7~24 캔들 변동률'),
    sa.Column('past_slope', sa.Numeric(precision=14, scale=6), nullable=True, comment='직전 구간 기울기'),
    sa.Column('past_std', sa.Numeric(precision=14, scale=6), nullable=True, comment='직전 구간 표준편차'),
    sa.Column('atr', sa.Numeric(precision=14, scale=6), nullable=True, comment='평균 변동성 (ATR)'),
    sa.Column('shape_vector', sa.ARRAY(sa.Float()), nullable=True, comment='무차원 형태 벡터 (2*m + 7 차원)'),
    sa.Column('vector_dim', sa.Integer(), nullable=True, comment='벡터 차원 수'),
    sa.Column('vector_m', sa.Integer(), nullable=True, comment='PAA 리샘플링 길이 m'),
    sa.Column('prior_candles', sa.Integer(), nullable=True, comment='시그널 이전 캔들 개수 (벡터 생성에 사용)'),
    sa.Column('signal_score', sa.Numeric(precision=5, scale=3), nullable=True, comment='시그널 스코어 (추후 확장용)'),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='탐지일시'),
    sa.ForeignKeyConstraint(['config_id'], ['trading.intraday_signal_detection_config.config_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('ticker_id', 'signal_datetime', 'config_id', name='uq_intraday_result_ticker_datetime_config'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_intraday_signal_detection_result_config_id'), 'intraday_signal_detection_result', ['config_id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_intraday_signal_detection_result_signal_datetime'), 'intraday_signal_detection_result', ['signal_datetime'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_intraday_signal_detection_result_ticker_id'), 'intraday_signal_detection_result', ['ticker_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_intraday_signal_detection_result_ticker_id'), table_name='intraday_signal_detection_result', schema='trading')
    op.drop_index(op.f('ix_trading_intraday_signal_detection_result_signal_datetime'), table_name='intraday_signal_detection_result', schema='trading')
    op.drop_index(op.f('ix_trading_intraday_signal_detection_result_config_id'), table_name='intraday_signal_detection_result', schema='trading')
    op.drop_table('intraday_signal_detection_result', schema='trading')
    op.drop_table('intraday_signal_detection_config', schema='trading')
    # ### end Alembic commands ###
