"""add_is_latest_to_analyst_recommendation

Revision ID: d8133874aa09
Revises: f1a2b3c4d5e6
Create Date: 2025-10-02 20:45:04.345680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8133874aa09'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyst_recommendation', sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False, comment='최신 추천 여부 (티커별로 1개만 true)'), schema='trading')
    op.create_index('idx_analyst_recommendation_ticker_latest', 'analyst_recommendation', ['ticker_id', 'is_latest'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_analyst_recommendation_is_latest'), 'analyst_recommendation', ['is_latest'], unique=False, schema='trading')
    op.alter_column('kis_portfolio_snapshot', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='API 응답 원본 JSON',
               existing_nullable=False,
               schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kis_portfolio_snapshot', 'raw_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='API 응답 원본 JSON',
               existing_nullable=False,
               schema='trading')
    op.drop_index(op.f('ix_trading_analyst_recommendation_is_latest'), table_name='analyst_recommendation', schema='trading')
    op.drop_index('idx_analyst_recommendation_ticker_latest', table_name='analyst_recommendation', schema='trading')
    op.drop_column('analyst_recommendation', 'is_latest', schema='trading')
    # ### end Alembic commands ###
