"""dart_corp_code_v2

Revision ID: d878e24ea28b
Revises: cd2883e5370d
Create Date: 2025-10-04 20:56:52.517192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd878e24ea28b'
down_revision: Union[str, Sequence[str], None] = 'cd2883e5370d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dart_corp_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='DART 기업코드 ID'),
    sa.Column('corp_code', sa.String(length=8), nullable=False, comment='기업 고유번호 (8자리) - DART corp_code'),
    sa.Column('corp_name', sa.String(length=100), nullable=False, comment='정식명칭 - 정식회사명칭'),
    sa.Column('corp_eng_name', sa.String(length=100), nullable=True, comment='영문 정식명칭 - 영문정식회사명칭'),
    sa.Column('stock_code', sa.String(length=6), nullable=True, comment='종목코드 (6자리) - 상장회사인 경우만 존재'),
    sa.Column('modify_date', sa.String(length=8), nullable=False, comment='최종변경일자 (YYYYMMDD)'),
    sa.Column('is_stock_listed', sa.Boolean(), nullable=False, comment='상장여부 - stock_code 존재 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성여부 - 현재 사용중인지 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정시간'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수집시간 - DART API 호출 시점'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code', name='uq_dart_corp_code'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_dart_corp_code_collected_at'), 'dart_corp_code', ['collected_at'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_corp_code'), 'dart_corp_code', ['corp_code'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_corp_name'), 'dart_corp_code', ['corp_name'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_id'), 'dart_corp_code', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_is_active'), 'dart_corp_code', ['is_active'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_is_stock_listed'), 'dart_corp_code', ['is_stock_listed'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_modify_date'), 'dart_corp_code', ['modify_date'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dart_corp_code_stock_code'), 'dart_corp_code', ['stock_code'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_dart_corp_code_stock_code'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_modify_date'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_is_stock_listed'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_is_active'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_id'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_corp_name'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_corp_code'), table_name='dart_corp_code', schema='trading')
    op.drop_index(op.f('ix_trading_dart_corp_code_collected_at'), table_name='dart_corp_code', schema='trading')
    op.drop_table('dart_corp_code', schema='trading')
    # ### end Alembic commands ###
