"""add kis

Revision ID: d9145f6fe554
Revises: c1338b282ccd
Create Date: 2025-09-26 07:40:09.258493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9145f6fe554'
down_revision: Union[str, Sequence[str], None] = 'c1338b282ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kis_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=256), nullable=False),
    sa.Column('appkey_hash', sa.String(length=128), nullable=False),
    sa.Column('tr_id', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.String(length=4096), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appkey_hash', 'tr_id', name='uq_kis_token_appkey_trid'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_kis_token_appkey_hash'), 'kis_token', ['appkey_hash'], unique=False, schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.drop_index(op.f('ix_trading_kis_token_appkey_hash'), table_name='kis_token', schema='trading')
    op.drop_table('kis_token', schema='trading')
    # ### end Alembic commands ###
