"""data_group

Revision ID: d9dac394421f
Revises: add_macro_group_tables
Create Date: 2025-09-29 08:57:10.068898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9dac394421f'
down_revision: Union[str, Sequence[str], None] = 'add_macro_group_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('macro_group', schema='trading')
    #op.drop_table('macro_group_series', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
