"""add news_v2

Revision ID: ded1bf26121f
Revises: bad5a509f660
Create Date: 2025-09-18 14:09:40.608758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded1bf26121f'
down_revision: Union[str, Sequence[str], None] = 'bad5a509f660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'FILTERED', 'ANALYZED', name='newsstatus'), nullable=False),
    sa.Column('is_finance_related', sa.Boolean(), nullable=False),
    sa.Column('content_status', sa.Enum('NONE', 'SUCCESS', 'FAILED_ONCE', 'FAILED_FINAL', name='contentstatus'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link'),
    schema='trading'
    )
    op.create_table('news_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['trading.news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('news_theme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['trading.news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['trading.theme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('news_ticker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['trading.news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_symbol'], ['trading.ticker.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_ticker', schema='trading')
    op.drop_table('news_theme', schema='trading')
    op.drop_table('news_summary', schema='trading')
    op.drop_table('news', schema='trading')
    # ### end Alembic commands ###
