"""add_fundamentals_tables

Revision ID: ea4b73b15365
Revises: bc77059171c7
Create Date: 2025-09-28 06:14:05.520215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4b73b15365'
down_revision: Union[str, Sequence[str], None] = 'bc77059171c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='배당 이력 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID'),
    sa.Column('ex_dividend_date', sa.Date(), nullable=False, comment='배당락일'),
    sa.Column('dividend_per_share', sa.Numeric(precision=10, scale=4), nullable=False, comment='주당 배당금'),
    sa.Column('dividend_yield', sa.Float(), nullable=True, comment='배당률 (%)'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='지급일'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 일시'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_dividend_history_id'), 'dividend_history', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_dividend_history_ticker_id'), 'dividend_history', ['ticker_id'], unique=False, schema='trading')
    op.create_table('fundamental_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='스냅샷 ID'),
    sa.Column('ticker_id', sa.Integer(), nullable=False, comment='티커 ID'),
    sa.Column('per', sa.Float(), nullable=True, comment='PER (주가수익비율)'),
    sa.Column('pbr', sa.Float(), nullable=True, comment='PBR (주가순자산비율)'),
    sa.Column('dividend_yield', sa.Float(), nullable=True, comment='배당률 (%)'),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True, comment='시가총액'),
    sa.Column('debt_ratio', sa.Float(), nullable=True, comment='부채비율 (%)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='업데이트 일시'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_fundamental_snapshot_id'), 'fundamental_snapshot', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_fundamental_snapshot_ticker_id'), 'fundamental_snapshot', ['ticker_id'], unique=False, schema='trading')
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False, comment='티커 심볼'), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.drop_index(op.f('ix_trading_fundamental_snapshot_ticker_id'), table_name='fundamental_snapshot', schema='trading')
    op.drop_index(op.f('ix_trading_fundamental_snapshot_id'), table_name='fundamental_snapshot', schema='trading')
    op.drop_table('fundamental_snapshot', schema='trading')
    op.drop_index(op.f('ix_trading_dividend_history_ticker_id'), table_name='dividend_history', schema='trading')
    op.drop_index(op.f('ix_trading_dividend_history_id'), table_name='dividend_history', schema='trading')
    op.drop_table('dividend_history', schema='trading')
    # ### end Alembic commands ###
