"""add signals v2

Revision ID: edb6a32cceb1
Revises: 7c88c8f35ad8
Create Date: 2025-10-11 23:32:13.960805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb6a32cceb1'
down_revision: Union[str, Sequence[str], None] = '7c88c8f35ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_detection_config', sa.Column('version', sa.String(length=10), server_default='v1', nullable=False, comment='알고리즘 버전 (탐지+벡터)'), schema='trading')
    op.drop_constraint(op.f('uq_trend_config_params'), 'trend_detection_config', schema='trading', type_='unique')
    op.create_unique_constraint('uq_trend_config_params', 'trend_detection_config', ['direction', 'lookback', 'future_window', 'min_change', 'max_reverse', 'flatness_k', 'atr_window', 'version'], schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trend_config_params', 'trend_detection_config', schema='trading', type_='unique')
    op.create_unique_constraint(op.f('uq_trend_config_params'), 'trend_detection_config', ['direction', 'lookback', 'future_window', 'min_change', 'max_reverse', 'flatness_k', 'atr_window'], schema='trading', postgresql_nulls_not_distinct=False)
    op.drop_column('trend_detection_config', 'version', schema='trading')
    # ### end Alembic commands ###
