"""order_status

Revision ID: ee3d4c11c244
Revises: 672bff21f279
Create Date: 2025-10-09 22:25:14.926160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3d4c11c244'
down_revision: Union[str, Sequence[str], None] = '672bff21f279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_fill', sa.Column('fill_status', sa.Text(), nullable=False, comment='체결상태(UNFILLED/PARTIAL/FULL/CANCELLED/REJECTED)'), schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_fill', 'fill_status', schema='trading')
    # ### end Alembic commands ###
