"""change_snapshot_id_from_uuid_to_auto_increment

Revision ID: ef41e080cabc
Revises: 17257a5e66eb
Create Date: 2025-10-02 04:07:00.478614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef41e080cabc'
down_revision: Union[str, Sequence[str], None] = '17257a5e66eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 데이터가 이미 삭제되었으므로 테이블을 삭제하고 다시 생성
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 외래키 제약조건 먼저 삭제
    op.drop_constraint('kis_account_totals_snapshot_id_fkey', 'kis_account_totals', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_currency_summary_snapshot_id_fkey', 'kis_currency_summary', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_position_execbasis_snapshot_id_fkey', 'kis_position_execbasis', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_position_execbasis_ticker_id_fkey', 'kis_position_execbasis', schema='trading', type_='foreignkey')
    
    # 테이블 삭제
    op.drop_table('kis_account_totals', schema='trading')
    op.drop_table('kis_currency_summary', schema='trading')
    op.drop_table('kis_position_execbasis', schema='trading')
    op.drop_table('kis_portfolio_snapshot', schema='trading')
    
    # 테이블 재생성 (Integer ID로)
    op.create_table('kis_portfolio_snapshot',
        sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False, comment='스냅샷 ID'),
        sa.Column('provider', sa.Text(), nullable=False, comment='제공사 (KIS 등)'),
        sa.Column('account_id', sa.Text(), nullable=False, comment='계좌 식별자'),
        sa.Column('venue_scope', sa.Text(), nullable=False, comment='시장 범위 (US/KR/ALL)'),
        sa.Column('asof_kst', sa.DateTime(timezone=True), nullable=False, comment='조회 기준 시각 (KST)'),
        sa.Column('raw_json', sa.JSON(), nullable=False, comment='API 응답 원본 JSON'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.PrimaryKeyConstraint('snapshot_id'),
        schema='trading'
    )
    
    op.create_table('kis_position_execbasis',
        sa.Column('snapshot_id', sa.Integer(), nullable=False, comment='스냅샷 ID'),
        sa.Column('symbol', sa.Text(), nullable=False, comment='종목코드 (티커)'),
        sa.Column('name', sa.Text(), comment='종목명'),
        sa.Column('exchange_code', sa.Text(), comment='거래소 코드 (NYSE/NASD 등)'),
        sa.Column('ticker_id', sa.Integer(), nullable=True, comment='티커 ID (핀헙 기반)'),
        sa.Column('ccy', sa.Text(), comment='통화코드 (USD/HKD/...)'),
        sa.Column('pos_qty_exec', sa.Numeric(precision=20, scale=8), comment='체결기준 현재 보유수량'),
        sa.Column('orderable_qty', sa.Numeric(precision=20, scale=8), comment='주문가능수량'),
        sa.Column('avg_cost_ccy', sa.Numeric(precision=20, scale=8), comment='평균매입단가 (통화 기준)'),
        sa.Column('last_price_ccy', sa.Numeric(precision=20, scale=8), comment='현재가 (통화 기준)'),
        sa.Column('purchase_amt_ccy', sa.Numeric(precision=20, scale=8), comment='매입금액 (통화 기준)'),
        sa.Column('eval_amt_ccy', sa.Numeric(precision=20, scale=8), comment='평가금액 (통화 기준)'),
        sa.Column('pnl_ccy', sa.Numeric(precision=20, scale=8), comment='평가손익금액 (통화 기준)'),
        sa.Column('pnl_rate', sa.Numeric(precision=10, scale=4), comment='평가손익율'),
        sa.Column('fx_rate_krw_per_ccy', sa.Numeric(precision=20, scale=8), comment='환율 (KRW/통화)'),
        sa.Column('std_pdno', sa.Text(), comment='표준상품번호 (ISIN 등)'),
        sa.Column('product_type_cd', sa.Text(), comment='상품유형코드'),
        sa.Column('security_type', sa.Text(), comment='유가증권구분명'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ),
        sa.PrimaryKeyConstraint('snapshot_id', 'symbol'),
        schema='trading'
    )
    
    op.create_table('kis_currency_summary',
        sa.Column('snapshot_id', sa.Integer(), nullable=False, comment='스냅샷 ID'),
        sa.Column('ccy', sa.Text(), nullable=False, comment='통화코드 (USD/HKD/JPY…)'),
        sa.Column('buy_amt_ccy_sum', sa.Numeric(precision=20, scale=8), comment='외화매수금액합계'),
        sa.Column('sell_amt_ccy_sum', sa.Numeric(precision=20, scale=8), comment='외화매도금액합계'),
        sa.Column('cash_ccy', sa.Numeric(precision=20, scale=8), comment='외화예수금액'),
        sa.Column('locked_margin_ccy', sa.Numeric(precision=20, scale=8), comment='외화매수증거금'),
        sa.Column('other_margin_ccy', sa.Numeric(precision=20, scale=8), comment='외화기타증거금'),
        sa.Column('withdrawable_ccy', sa.Numeric(precision=20, scale=8), comment='출금가능 외화금액'),
        sa.Column('portfolio_eval_ccy', sa.Numeric(precision=20, scale=8), comment='통화별 평가총액'),
        sa.Column('first_fx_krw_per_ccy', sa.Numeric(precision=20, scale=8), comment='최초고시환율'),
        sa.Column('local_custody_flag', sa.Text(), comment='현지보관통화여부'),
        sa.Column('nextday_withdrawable_ccy', sa.Numeric(precision=20, scale=8), comment='익일출금가능 외화금액'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.PrimaryKeyConstraint('snapshot_id', 'ccy'),
        schema='trading'
    )
    
    op.create_table('kis_account_totals',
        sa.Column('snapshot_id', sa.Integer(), nullable=False, comment='스냅샷 ID'),
        sa.Column('total_assets_krw', sa.Numeric(precision=20, scale=8), comment='총자산금액 (KRW)'),
        sa.Column('total_deposit_krw', sa.Numeric(precision=20, scale=8), comment='총예수금액 (KRW)'),
        sa.Column('withdrawable_total_krw', sa.Numeric(precision=20, scale=8), comment='인출가능총금액 (KRW)'),
        sa.Column('usable_fx_total_ccy', sa.Numeric(precision=20, scale=8), comment='외화사용가능금액합계'),
        sa.Column('locked_margin_krw', sa.Numeric(precision=20, scale=8), comment='매수증거금 총액 (KRW)'),
        sa.Column('unsettled_buy_krw', sa.Numeric(precision=20, scale=8), comment='미결제매수금액합계 (KRW)'),
        sa.Column('unsettled_sell_krw', sa.Numeric(precision=20, scale=8), comment='미결제매도금액합계 (KRW)'),
        sa.Column('fx_balance_total_ccy', sa.Numeric(precision=20, scale=8), comment='총외화잔고합계'),
        sa.Column('total_eval_pnl_krw', sa.Numeric(precision=20, scale=8), comment='총평가손익금액 (KRW)'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.PrimaryKeyConstraint('snapshot_id'),
        schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 외래키 제약조건 먼저 삭제
    op.drop_constraint('kis_account_totals_snapshot_id_fkey', 'kis_account_totals', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_currency_summary_snapshot_id_fkey', 'kis_currency_summary', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_position_execbasis_snapshot_id_fkey', 'kis_position_execbasis', schema='trading', type_='foreignkey')
    op.drop_constraint('kis_position_execbasis_ticker_id_fkey', 'kis_position_execbasis', schema='trading', type_='foreignkey')
    
    # 테이블 삭제
    op.drop_table('kis_account_totals', schema='trading')
    op.drop_table('kis_currency_summary', schema='trading')
    op.drop_table('kis_position_execbasis', schema='trading')
    op.drop_table('kis_portfolio_snapshot', schema='trading')
    
    # UUID 버전으로 테이블 재생성
    op.create_table('kis_portfolio_snapshot',
        sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='스냅샷 ID'),
        sa.Column('provider', sa.Text(), nullable=False, comment='제공사 (KIS 등)'),
        sa.Column('account_id', sa.Text(), nullable=False, comment='계좌 식별자'),
        sa.Column('venue_scope', sa.Text(), nullable=False, comment='시장 범위 (US/KR/ALL)'),
        sa.Column('asof_kst', sa.DateTime(timezone=True), nullable=False, comment='조회 기준 시각 (KST)'),
        sa.Column('raw_json', sa.JSON(), nullable=False, comment='API 응답 원본 JSON'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.PrimaryKeyConstraint('snapshot_id'),
        schema='trading'
    )
    
    op.create_table('kis_position_execbasis',
        sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='스냅샷 ID'),
        sa.Column('symbol', sa.Text(), nullable=False, comment='종목코드 (티커)'),
        sa.Column('name', sa.Text(), comment='종목명'),
        sa.Column('exchange_code', sa.Text(), comment='거래소 코드 (NYSE/NASD 등)'),
        sa.Column('ticker_id', sa.Integer(), nullable=True, comment='티커 ID (핀헙 기반)'),
        sa.Column('ccy', sa.Text(), comment='통화코드 (USD/HKD/...)'),
        sa.Column('pos_qty_exec', sa.Numeric(precision=20, scale=8), comment='체결기준 현재 보유수량'),
        sa.Column('orderable_qty', sa.Numeric(precision=20, scale=8), comment='주문가능수량'),
        sa.Column('avg_cost_ccy', sa.Numeric(precision=20, scale=8), comment='평균매입단가 (통화 기준)'),
        sa.Column('last_price_ccy', sa.Numeric(precision=20, scale=8), comment='현재가 (통화 기준)'),
        sa.Column('purchase_amt_ccy', sa.Numeric(precision=20, scale=8), comment='매입금액 (통화 기준)'),
        sa.Column('eval_amt_ccy', sa.Numeric(precision=20, scale=8), comment='평가금액 (통화 기준)'),
        sa.Column('pnl_ccy', sa.Numeric(precision=20, scale=8), comment='평가손익금액 (통화 기준)'),
        sa.Column('pnl_rate', sa.Numeric(precision=10, scale=4), comment='평가손익율'),
        sa.Column('fx_rate_krw_per_ccy', sa.Numeric(precision=20, scale=8), comment='환율 (KRW/통화)'),
        sa.Column('std_pdno', sa.Text(), comment='표준상품번호 (ISIN 등)'),
        sa.Column('product_type_cd', sa.Text(), comment='상품유형코드'),
        sa.Column('security_type', sa.Text(), comment='유가증권구분명'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.ForeignKeyConstraint(['ticker_id'], ['trading.ticker.id'], ),
        sa.PrimaryKeyConstraint('snapshot_id', 'symbol'),
        schema='trading'
    )
    
    op.create_table('kis_currency_summary',
        sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='스냅샷 ID'),
        sa.Column('ccy', sa.Text(), nullable=False, comment='통화코드 (USD/HKD/JPY…)'),
        sa.Column('buy_amt_ccy_sum', sa.Numeric(precision=20, scale=8), comment='외화매수금액합계'),
        sa.Column('sell_amt_ccy_sum', sa.Numeric(precision=20, scale=8), comment='외화매도금액합계'),
        sa.Column('cash_ccy', sa.Numeric(precision=20, scale=8), comment='외화예수금액'),
        sa.Column('locked_margin_ccy', sa.Numeric(precision=20, scale=8), comment='외화매수증거금'),
        sa.Column('other_margin_ccy', sa.Numeric(precision=20, scale=8), comment='외화기타증거금'),
        sa.Column('withdrawable_ccy', sa.Numeric(precision=20, scale=8), comment='출금가능 외화금액'),
        sa.Column('portfolio_eval_ccy', sa.Numeric(precision=20, scale=8), comment='통화별 평가총액'),
        sa.Column('first_fx_krw_per_ccy', sa.Numeric(precision=20, scale=8), comment='최초고시환율'),
        sa.Column('local_custody_flag', sa.Text(), comment='현지보관통화여부'),
        sa.Column('nextday_withdrawable_ccy', sa.Numeric(precision=20, scale=8), comment='익일출금가능 외화금액'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.PrimaryKeyConstraint('snapshot_id', 'ccy'),
        schema='trading'
    )
    
    op.create_table('kis_account_totals',
        sa.Column('snapshot_id', sa.UUID(), nullable=False, comment='스냅샷 ID'),
        sa.Column('total_assets_krw', sa.Numeric(precision=20, scale=8), comment='총자산금액 (KRW)'),
        sa.Column('total_deposit_krw', sa.Numeric(precision=20, scale=8), comment='총예수금액 (KRW)'),
        sa.Column('withdrawable_total_krw', sa.Numeric(precision=20, scale=8), comment='인출가능총금액 (KRW)'),
        sa.Column('usable_fx_total_ccy', sa.Numeric(precision=20, scale=8), comment='외화사용가능금액합계'),
        sa.Column('locked_margin_krw', sa.Numeric(precision=20, scale=8), comment='매수증거금 총액 (KRW)'),
        sa.Column('unsettled_buy_krw', sa.Numeric(precision=20, scale=8), comment='미결제매수금액합계 (KRW)'),
        sa.Column('unsettled_sell_krw', sa.Numeric(precision=20, scale=8), comment='미결제매도금액합계 (KRW)'),
        sa.Column('fx_balance_total_ccy', sa.Numeric(precision=20, scale=8), comment='총외화잔고합계'),
        sa.Column('total_eval_pnl_krw', sa.Numeric(precision=20, scale=8), comment='총평가손익금액 (KRW)'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['trading.kis_portfolio_snapshot.snapshot_id'], ),
        sa.PrimaryKeyConstraint('snapshot_id'),
        schema='trading'
    )
    # ### end Alembic commands ###
