"""add simil v5

Revision ID: ef5fa180d97d
Revises: 4a72c8635c56
Create Date: 2025-10-14 03:24:08.289080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5fa180d97d'
down_revision: Union[str, Sequence[str], None] = '4a72c8635c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarity_analysis', sa.Column('ticker_name_ko', sa.String(length=255), nullable=True, comment='종목명 (한글)'), schema='trading')
    op.add_column('similarity_analysis', sa.Column('top_similarity', sa.Numeric(precision=10, scale=6), nullable=False, server_default='0', comment='가장 높은 유사도 점수 (TOP 1)'), schema='trading')
    op.drop_index(op.f('ix_trading_similarity_analysis_analysis_date'), table_name='similarity_analysis', schema='trading')
    op.drop_constraint(op.f('uq_similarity_ticker_date'), 'similarity_analysis', schema='trading', type_='unique')
    op.drop_index(op.f('ix_trading_similarity_analysis_ticker_id'), table_name='similarity_analysis', schema='trading')
    op.create_index(op.f('ix_trading_similarity_analysis_ticker_id'), 'similarity_analysis', ['ticker_id'], unique=True, schema='trading')
    op.create_unique_constraint('uq_similarity_ticker', 'similarity_analysis', ['ticker_id'], schema='trading')
    op.drop_column('similarity_analysis', 'analysis_date', schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarity_analysis', sa.Column('analysis_date', sa.DATE(), autoincrement=False, nullable=False, comment='분석 기준 날짜'), schema='trading')
    op.drop_constraint('uq_similarity_ticker', 'similarity_analysis', schema='trading', type_='unique')
    op.drop_index(op.f('ix_trading_similarity_analysis_ticker_id'), table_name='similarity_analysis', schema='trading')
    op.create_index(op.f('ix_trading_similarity_analysis_ticker_id'), 'similarity_analysis', ['ticker_id'], unique=False, schema='trading')
    op.create_unique_constraint(op.f('uq_similarity_ticker_date'), 'similarity_analysis', ['ticker_id', 'analysis_date'], schema='trading', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trading_similarity_analysis_analysis_date'), 'similarity_analysis', ['analysis_date'], unique=False, schema='trading')
    op.drop_column('similarity_analysis', 'top_similarity', schema='trading')
    op.drop_column('similarity_analysis', 'ticker_name_ko', schema='trading')
    # ### end Alembic commands ###
