"""is_active

Revision ID: f06228edda61
Revises: 00fe5afe5cfa
Create Date: 2025-09-29 08:27:14.369234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06228edda61'
down_revision: Union[str, Sequence[str], None] = '00fe5afe5cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macro_data_series', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='사용유무'), schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('macro_data_series', 'is_active', schema='trading')
    # ### end Alembic commands ###
