"""news_exchange

Revision ID: f54868c6b299
Revises: add_analyst_recommendation_table
Create Date: 2025-09-30 08:42:34.968882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f54868c6b299'
down_revision: Union[str, Sequence[str], None] = 'add_analyst_recommendation_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_exchange',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='뉴스 거래소 매핑 ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='뉴스 ID'),
    sa.Column('exchange_code', sa.String(length=10), nullable=False, comment='거래소 코드 (예: NMS, NYQ, TSE)'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='신뢰도'),
    sa.Column('method', sa.String(length=50), nullable=True, comment='매핑 방법'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['news_id'], ['trading.news.id'], name=op.f('news_exchange_news_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('news_exchange_pkey')),
    sa.UniqueConstraint('news_id', 'exchange_code', name=op.f('uq_news_exchange__news_exchange')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_exchange', schema='trading')
    # ### end Alembic commands ###
