"""add fred v2

Revision ID: fbf1b21eb41d
Revises: 5cda4a5dfdc2
Create Date: 2025-09-23 03:29:00.926663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf1b21eb41d'
down_revision: Union[str, Sequence[str], None] = '5cda4a5dfdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_data_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fred_series_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('units', sa.String(length=128), nullable=True),
    sa.Column('seasonal_adjustment', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observation_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fred_series_id', name='uq_macro_series_fred_id'),
    schema='trading'
    )
    op.create_table('macro_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_macro_indicator_code'),
    schema='trading'
    )
    op.create_table('macro_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('event_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('actual', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('consensus', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('previous', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('surprise', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('is_revised', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'event_code', 'event_time', name='uq_release_key'),
    schema='trading'
    )
    op.create_table('macro_data_series_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('vintage_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['trading.macro_data_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'obs_date', 'vintage_start', name='uq_macro_value_vintage'),
    schema='trading'
    )
    op.create_table('macro_indicator_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('fred_series_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['trading.macro_indicator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'fred_series_id', name='uq_indicator_series'),
    schema='trading'
    )
    #op.add_column('ticker_fundamentals', sa.Column('ticker_symbol', sa.String(), nullable=False), schema='trading')
    #op.create_foreign_key(None, 'ticker_fundamentals', 'ticker', ['ticker_symbol'], ['symbol'], source_schema='trading', referent_schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'ticker_fundamentals', schema='trading', type_='foreignkey')
    #op.drop_column('ticker_fundamentals', 'ticker_symbol', schema='trading')
    op.drop_table('macro_indicator_series', schema='trading')
    op.drop_table('macro_data_series_value', schema='trading')
    op.drop_table('macro_release', schema='trading')
    op.drop_table('macro_indicator', schema='trading')
    op.drop_table('macro_data_series', schema='trading')
    # ### end Alembic commands ###
