"""add title_ko

Revision ID: fd7bf907382e
Revises: 192bf31e8a69
Create Date: 2025-09-19 00:13:32.569557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd7bf907382e'
down_revision: Union[str, Sequence[str], None] = '192bf31e8a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_summary', sa.Column('title_localized', sa.String(length=300), nullable=True), schema='trading')

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('news_summary', 'title_localized', schema='trading')
    # ### end Alembic commands ###
