"""modify_market_holiday_table

Revision ID: modify_market_holiday_table
Revises: add_market_holidays_table
Create Date: 2024-01-15 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'modify_market_holiday_table'
down_revision = 'add_market_holidays_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 테이블 삭제 후 새로 생성
    op.drop_constraint('uq_market_holiday_exchange_date', 'market_holiday', type_='unique', schema='trading')
    op.drop_index(op.f('ix_market_holiday_holiday_date'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_exchange'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_id'), table_name='market_holiday', schema='trading')
    op.drop_table('market_holiday', schema='trading')
    
    # 새로운 구조로 테이블 생성
    op.create_table('market_holiday',
    sa.Column('id', sa.Integer(), nullable=False, comment='휴일 ID'),
    sa.Column('exchange', sa.String(length=10), nullable=False, comment='거래소 코드 (예: US, KR, JP)'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='거래소 타임존 (예: America/New_York)'),
    sa.Column('at_date', sa.Date(), nullable=False, comment='휴일 날짜 (atDate)'),
    sa.Column('event_name', sa.String(length=100), nullable=False, comment='휴일명 (eventName)'),
    sa.Column('trading_hour', sa.String(length=20), nullable=True, comment='거래 시간 (tradingHour, 빈값이면 완전휴일)'),
    sa.Column('is_open', sa.Boolean(), nullable=False, comment='해당 날짜 거래소 개장 여부 (tradingHour 기반)'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_market_holiday_id'), 'market_holiday', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_exchange'), 'market_holiday', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_at_date'), 'market_holiday', ['at_date'], unique=False, schema='trading')
    op.create_unique_constraint('uq_market_holiday_exchange_date', 'market_holiday', ['exchange', 'at_date'], schema='trading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_holiday_exchange_date', 'market_holiday', type_='unique', schema='trading')
    op.drop_index(op.f('ix_market_holiday_at_date'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_exchange'), table_name='market_holiday', schema='trading')
    op.drop_index(op.f('ix_market_holiday_id'), table_name='market_holiday', schema='trading')
    op.drop_table('market_holiday', schema='trading')
    
    # 기존 구조로 복원
    op.create_table('market_holiday',
    sa.Column('id', sa.Integer(), nullable=False, comment='휴일 ID'),
    sa.Column('exchange', sa.String(length=10), nullable=False, comment='거래소 코드 (예: US, KR, JP)'),
    sa.Column('country', sa.String(length=10), nullable=False, comment='국가 코드 (예: US, KR, JP)'),
    sa.Column('holiday_date', sa.Date(), nullable=False, comment='휴일 날짜'),
    sa.Column('holiday_name', sa.String(length=100), nullable=False, comment='휴일명'),
    sa.Column('is_open', sa.Boolean(), nullable=False, comment='해당 날짜 거래소 개장 여부'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_market_holiday_id'), 'market_holiday', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_exchange'), 'market_holiday', ['exchange'], unique=False, schema='trading')
    op.create_index(op.f('ix_market_holiday_holiday_date'), 'market_holiday', ['holiday_date'], unique=False, schema='trading')
    op.create_unique_constraint('uq_market_holiday_exchange_date', 'market_holiday', ['exchange', 'holiday_date'], schema='trading')
    # ### end Alembic commands ###
